#!/bin/bash
# Build and package one Crispy engine for PS3.
#
#   ./ps3/build.sh doom
#   ./ps3/build.sh heretic
#   ./ps3/build.sh hexen
#
# Rewrites ps3/appid.mk, reconfigures cmake so the per-game defines are
# picked up, builds, and packages -- in that order, with set -e, so a
# failed build can never leave a .pkg made from the previous binary.
set -e

GAME="$1"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

case "$GAME" in
    doom)    APPID=CRISPDOOM; TITLE="Crispy Doom" ;;
    heretic) APPID=CRISPHERE; TITLE="Crispy Heretic" ;;
    hexen)   APPID=CRISPHEX1; TITLE="Crispy Hexen" ;;
    strife)  APPID=CRISPSTRF; TITLE="Crispy Strife" ;;
    *) echo "uso: $0 {doom|heretic|hexen|strife}"; exit 1 ;;
esac

cat > "$ROOT/ps3/appid.mk" << EOF
# Which Crispy engine this package builds. Drives the CMake target, the
# executable name, the IWADs the launcher offers, and the .pkg contents.
# One of: doom heretic hexen strife
#
# Generated by ps3/build.sh -- edit that instead.
PS3_GAME  := $GAME

# APPID must be exactly 9 characters: the PS3 pads shorter ones with an
# underscore, which silently breaks every path built from it.
PS3_APPID := $APPID
PS3_TITLE := $TITLE
EOF

cd "$ROOT/build-ps3"

# Wipe the object tree when the engine changes. The per-game defines
# come from appid.mk via file(STRINGS), and cmake rewrites flags.make on
# reconfigure but does not mark the already-built objects stale -- so a
# switch would silently reuse the previous game's i_ps3launcher.c.obj,
# launcher title and all.
STAMP="$ROOT/build-ps3/.ps3_game"
if [ ! -f "$STAMP" ] || [ "$(cat "$STAMP")" != "$GAME" ]; then
    echo "engine changed -> clearing object tree"
    rm -rf "$ROOT/build-ps3/src/CMakeFiles"
    echo "$GAME" > "$STAMP"
fi

cmake .. -DCMAKE_TOOLCHAIN_FILE=../ps3/crispy-ps3-toolchain.cmake -DPS3_BUILD=ON 2>&1 | grep -i "ps3 appid"
make "crispy-$GAME" 2>&1 | tail -3

cd src
rm -rf build "crispy-$GAME.self" "crispy-$GAME.pkg" \
       "crispy-$GAME.gnpdrm.pkg" "crispy-$GAME.fake.self"
cp "crispy-$GAME" "crispy-$GAME.elf"
make -f ../../Makefile.crispypkg 2>&1 | tail -2
cp "crispy-$GAME.gnpdrm.pkg" "$ROOT/Crispy$(tr a-z A-Z <<< "${GAME:0:1}")${GAME:1}-1.0.pkg"

echo
echo "=== LISTO: Crispy$(tr a-z A-Z <<< "${GAME:0:1}")${GAME:1}-1.0.pkg ($APPID) ==="
ls -la "$ROOT/Crispy$(tr a-z A-Z <<< "${GAME:0:1}")${GAME:1}-1.0.pkg"
